package com.example.myproject;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Splits an aggregated F Prime telemetry channel packet (Fw::TlmPacket) into
 * single-entry CCSDS space packets.
 * <p>
 * F Prime's Svc.TlmChan batches multiple telemetry channel entries into a single
 * Fw::TlmPacket which is downlinked as one CCSDS space packet. Each entry is:
 *
 * <pre>
 * channel id (4 bytes, big-endian U32)
 * F Prime time tag (time base 2B + time context 1B + seconds 4B + microseconds 4B)
 * serialized channel value (variable length, NOT length-prefixed)
 * </pre>
 *
 * The XTCE containers generated by fprime-xtce match one channel per packet, so
 * without splitting only the first entry of a batched packet is decoded. This class
 * walks the entries using a channel-id to serialized-value-size map derived from the
 * F Prime JSON dictionary and re-emits each entry as its own CCSDS packet with a
 * reconstructed primary header and the original per-entry time tag.
 */
public class TlmPacketSplitter {

    /** Size map marker: value is a string, walkable via its 2-byte length prefix */
    public static final int SIZE_STRING = -1;
    /** Size map marker: value size is unknown (variable-size non-string type) */
    public static final int SIZE_UNKNOWN = 0;

    // CCSDS/F Prime layout constants
    private static final int SPACE_PACKET_HEADER_LEN = 6;
    private static final int PACKET_DESCRIPTOR_SIZE = 2;
    private static final int CHAN_ID_SIZE = 4;
    private static final int TIME_TAG_SIZE = 2 + 1 + 4 + 4; // base + context + seconds + microseconds
    private static final int ENTRY_HEADER_SIZE = CHAN_ID_SIZE + TIME_TAG_SIZE;
    private static final int ENTRIES_OFFSET = SPACE_PACKET_HEADER_LEN + PACKET_DESCRIPTOR_SIZE;

    // Offsets within an entry
    private static final int TIME_SECONDS_OFFSET = CHAN_ID_SIZE + 2 + 1;
    private static final int TIME_MICROS_OFFSET = TIME_SECONDS_OFFSET + 4;

    // Same leap-seconds handling as FprimePacketPreprocessor, see
    // https://docs.yamcs.org/yamcs-server-manual/general/time/
    private static final int LEAP_SECONDS_OFFSET = 38;

    /** One split telemetry channel entry, repackaged as a standalone CCSDS packet */
    public static class SplitEntry {
        public final long channelId;
        public final byte[] packet;
        public final long generationTime;
        public final int apidSeqCount;
        public final boolean doNotArchive;

        SplitEntry(long channelId, byte[] packet, long generationTime, int apidSeqCount, boolean doNotArchive) {
            this.channelId = channelId;
            this.packet = packet;
            this.generationTime = generationTime;
            this.apidSeqCount = apidSeqCount;
            this.doNotArchive = doNotArchive;
        }
    }

    /** Reported when the entry walk cannot continue */
    public static class SplitException extends Exception {
        public SplitException(String message) {
            super(message);
        }
    }

    private final Map<Long, Integer> channelValueSizes;
    private final Set<Long> doNotArchiveChannelIds;
    private int sequenceCount = 0;

    public TlmPacketSplitter(Map<Long, Integer> channelValueSizes, Set<Long> doNotArchiveChannelIds) {
        this.channelValueSizes = channelValueSizes;
        this.doNotArchiveChannelIds = doNotArchiveChannelIds;
    }

    /**
     * Split an aggregated telemetry packet into single-entry CCSDS packets.
     *
     * @param bytes full CCSDS space packet (primary header + F Prime packet descriptor + entries)
     * @return one SplitEntry per telemetry channel entry found in the packet
     * @throws SplitException if the packet cannot be fully walked; entries parsed before the
     *             failure are lost and the caller should fall back to forwarding the original packet
     */
    public synchronized List<SplitEntry> split(byte[] bytes) throws SplitException {
        if (bytes.length < ENTRIES_OFFSET + ENTRY_HEADER_SIZE) {
            throw new SplitException("Packet too short to contain a telemetry channel entry: " + bytes.length);
        }
        List<SplitEntry> entries = new ArrayList<>();
        ByteBuffer buffer = ByteBuffer.wrap(bytes);
        int offset = ENTRIES_OFFSET;
        while (offset < bytes.length) {
            if (offset + ENTRY_HEADER_SIZE > bytes.length) {
                throw new SplitException("Trailing bytes too short for a telemetry channel entry at offset "
                        + offset + " of " + bytes.length);
            }
            long channelId = buffer.getInt(offset) & 0xFFFFFFFFL;
            int valueLength = valueLength(buffer, bytes.length, offset, channelId);
            int entryLength = ENTRY_HEADER_SIZE + valueLength;
            if (offset + entryLength > bytes.length) {
                throw new SplitException("Telemetry channel " + channelId + " entry at offset " + offset
                        + " overruns packet of length " + bytes.length);
            }
            entries.add(makeEntry(bytes, offset, entryLength, channelId));
            offset += entryLength;
        }
        return entries;
    }

    private int valueLength(ByteBuffer buffer, int packetLength, int offset, long channelId) throws SplitException {
        Integer size = channelValueSizes.get(channelId);
        if (size == null) {
            throw new SplitException("Unknown telemetry channel id " + channelId + " at offset " + offset);
        }
        if (size > 0) {
            return size;
        }
        if (size == SIZE_STRING) {
            int lengthOffset = offset + ENTRY_HEADER_SIZE;
            if (lengthOffset + 2 > packetLength) {
                throw new SplitException("String telemetry channel " + channelId + " at offset " + offset
                        + " is missing its length prefix");
            }
            return 2 + (buffer.getShort(lengthOffset) & 0xFFFF);
        }
        throw new SplitException("Telemetry channel " + channelId
                + " has a variable-size non-string type; cannot determine entry length");
    }

    private SplitEntry makeEntry(byte[] bytes, int offset, int entryLength, long channelId) {
        byte[] packet = new byte[ENTRIES_OFFSET + entryLength];
        // Copy the original primary header + F Prime packet descriptor, then the entry
        System.arraycopy(bytes, 0, packet, 0, ENTRIES_OFFSET);
        System.arraycopy(bytes, offset, packet, ENTRIES_OFFSET, entryLength);

        ByteBuffer out = ByteBuffer.wrap(packet);
        // Sequence flags "11" (unsegmented) + our own incrementing sequence count
        sequenceCount = (sequenceCount + 1) & 0x3FFF;
        short seqField = (short) (0xC000 | sequenceCount);
        out.putShort(4, (short) (packet.length - SPACE_PACKET_HEADER_LEN - 1)); // CCSDS length field first
        out.putShort(2, seqField);
        int apidSeqCount = out.getInt(0);

        // Per-entry generation time from the F Prime time tag
        int timeSec = out.getInt(ENTRIES_OFFSET + TIME_SECONDS_OFFSET) + LEAP_SECONDS_OFFSET;
        int timeUsec = out.getInt(ENTRIES_OFFSET + TIME_MICROS_OFFSET);
        long generationTime = (timeSec * 1000L) + (timeUsec / 1000L);

        boolean doNotArchive = doNotArchiveChannelIds.contains(channelId);
        return new SplitEntry(channelId, packet, generationTime, apidSeqCount, doNotArchive);
    }
}
